# header - menu
menu:
  Home: /
  About: /about
  Contact: /contact
  Friends: /links
  Github: https://github.com/jiasm

post_menu_side: right  # 默认 right

favicon:
  small: null
  medium: null
  apple_touch_icon: null
  safari_pinned_tab: null
